### ISSUE TITLE
installation: harmonise pytest version across REANA

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/pytest-reana#41]
Currently we have:

```console
~/reanahub $ rg 'pytest>|pytest<|pytest='
reana-commons/setup.py
31:    'pytest>=3.8'

reana-workflow-engine-cwl/setup.py
34:    'pytest>=2.8.0',

pytest-reana/setup.py
55:    'pytest>=3.8.0,<4.0.0',

reana-job-controller/setup.py
30:    'pytest>=2.8.0',

reana-message-broker/setup.py
29:    'pytest>=2.8.0',

reana-client/setup.py
27:    'pytest>=3.8.0,<4.0.0',

reana-workflow-monitor/setup.py
28:    'pytest>=2.8.0',

reana-workflow-controller/setup.py
30:    'pytest>=3.8.0,<4.0.0',

reana-server/setup.py
32:    'pytest>=3.8.0,<4.0.0',

reana-workflow-engine-serial/setup.py
30:    'pytest>=2.8.0,<3.0.0'

reana-db/setup.py
30:    'pytest>=2.8.0,<3.0.0'

reana-cluster/setup.py
29:    'pytest>=2.8.0'

reana/setup.py
29:    'pytest>=2.8.0',

reana-workflow-engine-yadage/setup.py
29:    'pytest>=2.8.0',
```

We should:
- [ ] Remove upper boundaries
- [ ] Set the same minimum version everywhere

**Comment by okraskaj** [comment]
For reana-message-broker this dependency should be removed.

**Comment by okraskaj** [comment]
- [ ] reana-commons
- [ ] reana-workflow-engine-cwl
- [ ] pytest-reana
- [ ] reana-job-controller
- [ ] reana-message-broker
- [ ] reana-client
- [ ] reana-workflow-monitor
- [ ] reana-workflow-controller
- [ ] reana-server/setup.py
- [ ] reana-workflow-engine-serial/setup.py
- [ ] reana-db/setup.py
- [ ] reana-cluster/setup.py
- [ ] reana/setup.py
- [ ] reana-workflow-engine-yadage/setup.py
